### ISSUE TITLE
練功房練習題所需Json

### ISSUE THREAD

**Issue by marklin-latte** [BatonHunter/BatonHunterRestfulServer#10]
該Json為選擇職業後，進入練功房，依職業所產生的練功房題目json。

Ex. get     /jobs/1/tutorials 就會回傳下面題目 

｛
　"id":1,
　”jobId”:1,
 　"title":"錢是甚麼?",
  　"content":"錢是一種可以「交換」的價值。在沒有錢的概念之前,人們只能用「以物易物」來交換價值。從古至今,錢可以用各種形式存在,比如說,黃金。重點是,只要「大家都同意」這是可以交換的價值,那這東西就可以當作錢來使用。現在的世界上,貨幣(像美金)就是錢,是以國家的「信用」為擔保,讓大家都能同意那是可以拿來交換的價值。",
　  "imagePath": "./components/trainingRoom_page/data/img/cat.gif"
},
  {
　"id":2,
　”jobId”:1,
    "title":"資本主義是啥?",
    "content":"錢是投資中必須要知道的一種交換價值,而投資中必須要知道的一種根本概念是資本主義,這是一種基本假設。資本主義(Capitalism),特色是私人擁有資本財產(生產工具),且投資活動是由個人決策左右,而非由國家所控制,經濟行為則以尋求利潤為目標。主要經濟模式包括自由的資本和雇傭流動、市場競爭、以及價格機制的運行。一般普遍認為資本主義在西方世界的封建制度崩壞之後成為了最主要的經濟模式。",
    "imagePath": "./components/trainingRoom_page/data/img/littlepony.png"
    }

**Comment by git03394538** [comment]
Just finished user job and task creation together with delete function. 

Gonna implement this very soon

**Comment by git03394538** [comment]
I will prefer to use task instead of tutorials.

**Comment by marklin-latte** [comment]
Ok ~~ I prefer to task too , and  don't ask me why i use tutorials ~ because I don't know too ~

**Comment by git03394538** [comment]
@h091237557 

This is how full data will be looked like. and I am implementing the logic in order to retrieve certain specific item base on id. Please let me know if this is ok for you. 

[{"title":"精英管理","imgPath":"www.google.com","jobs":[{"id":0,"jobId":1,"title":"投資","imgPath":"www.google.com","description":"投資關卡簡介\n歡迎您選擇投資領域,習得此項能力,代表您將能夠了解資本流動方式。\n擁有此能力者,將能更了解產業趨勢,資金流動規則,進而達到將資產配置到\n適當位置,產生更多報酬,讓資本為您所用,錢滾錢,越滾越多。\n1. 研究世界經濟發展趨勢,並且協助投資企業因應劇烈變化的通貨膨脹局勢,\n做出在使用原物料正確的避險決定。實際避免了一間投資企業的破產。\n2. 研究各產業的發展趨勢,早一步判斷趨勢,幫助公司挑選出具有成長潛力的\n投資企業及機會,創造出好的財務報酬。\n3. 研究各種不同類型的投資理論,促進與其他投資人密切關係,建立人脈,同\n時幫助公司做出正確的投資決策。\n4. 為了評估一間企業的價值,使用財務理論,分析企業財務報表,建立財務模\n型,幫助公司了解企業內容,以利投資決策。\n5. 與潛在投資對象接觸時,使用本身的知識基礎,談判能力,促進與企業主的\n順暢溝通,增進未來的投資機會。","tasks":[{"id":0,"taskId":1,"title":"錢是什麼","content":"錢是一種可以「交換」的價值。在沒有錢的概念之前,人們只能用「以物易物\n」來交換價值。從古至今,錢可以用各種形式存在,比如說,黃金。重點是,\n只要「大家都同意」這是可以交換的價值,那這東西就可以當作錢來使用。現\n在的世界上,貨幣(像美金)就是錢,是以國家的「信用」為擔保,讓大家都能\n同意那是可以拿來交換的價值。","imgPath":"www.google.com","questions":[{"answer":"false","content":"錢是一種可以拿來「賭博」的價值。","hint":"周潤發","title":"錢是什麼","type":"tf"},{"answer":"true","content":"只要大家都同意,甚麼事物都可以拿來當錢使用。","hint":"看看\u003c錢買不到的東西\u003e","title":"錢是什麼","type":"tf"},{"answer":["1"],"answerList":["A.以物易物","B.以暴制暴","C.以牙還牙","D.契約合同"],"content":"在沒有錢的觀念以前,人們可能用甚麼方式來交換價值?","hint":"暴力不能解決問題!!","title":"錢是什麼","type":"ch"},{"answer":["3"],"answerList":["A.農產品","B.GDP","C.國家信用","D.軍隊"],"content":"貨幣以甚麼為擔保?","hint":"希臘問題上出狀況的是?","title":"錢是什麼","type":"ch"},{"answer":[{"atd":"美國","atxt":"美金"},{"atd":"國家","atxt":"貨幣"},{"atd":"英國","atxt":"英鎊"}],"content":"請把下列物品聯繫在一起","hint":"國家的貨幣","title":"錢是什麼","type":"linkQuestion"}]}]}]}]

**Comment by marklin-latte** [comment]
OK~ fight~

**Comment by git03394538** [comment]
resolved in the latest version
